### ISSUE TITLE
Plots not created when param_estimation is executed on SGE/LSF cluster

### ISSUE THREAD

**Issue by pdp10** [pdp10/sb_pipe#58]
Received the following error, when running: 
[dallepep@rocks1 Working_Folder]$ python ../../../sb_pipe/run_sb_pipe.py -e sge_insulin_receptor_param_estim_copasi.conf 

The problems seems to be in utils/R/param_estim_utils.r

In fun(libname, pkgname) : no DISPLAY variable so Tk is not available
Saving 7 x 7 in image
Saving 7 x 7 in image
Error in grid.Call.graphics(L_raster, x$raster, x$x, x$y, x$width, x$height,  : 
  Empty raster
Calls: main ... drawDetails -> drawDetails.rastergrob -> grid.Call.graphics
In addition: Warning message:
position_stack requires constant width: output may be incorrect 
Execution halted

**Comment by wikiselev** [comment]
If you could run the first part of the R script in R console:
```
d <- read.table("results/obj-values.txt", header = F, sep = "\t")
models <- head(d[,1], 10)
dat <- read.table(paste0("results/", models[1], "/estd-params.txt"), header = T, sep = "\t")
for(i in models) {
  t <- read.table(paste0("results/", i, "/estd-params.txt"), header = T, sep = "\t")
  dat <- cbind(dat, t[,2])
}
rownames(dat) <- dat[,1]
dat <- dat[, c(5:dim(dat)[2])]
colnames(dat) <- models
```

and save dat variable like `saveRDS(d, "for_vlad.rds")` and send to me.

Then I should be able to see what the problem with ggplot is.

**Comment by pdp10** [comment]
Thanks Vladimir :+1: 
I see what I can do. It could be that that is a problem with grid rather than ggplot though. Not sure if I have to add a command to suppress something when no display is used. Eventually this is the only difference between executing the pipeline on the cluster or on the desktop.

**Comment by wikiselev** [comment]
It maybe the ggplot version problem. I has been recently updated to v2.0, so some old code could become wrong. Try to get the same version of ggplot on the cluster, as the one you have on your desktop.

**Comment by pdp10** [comment]
More info. 
In the error message: 
```
In fun(libname, pkgname) : no DISPLAY variable so Tk is not available
Saving 7 x 7 in image
Saving 7 x 7 in image
Error in grid.Call.graphics(L_raster, x$raster, x$x, x$y, x$width, x$height, : 
```

The error occurs for the second image. 
Looking at the code, the first image is a histogram, while the second one is a scatter plot: 
```
histogramplot <- function(dfCol, fileout) {
  g = ggplot(dfCol, aes_string(x=colnames(dfCol))) +
    geom_histogram(binwidth=density(dfCol[,])$bw, colour="black", fill="blue")
  ggsave(fileout, dpi=300)
  return(g)
}
```
```
scatterplot <- function(df, colNameX, colNameY, colNameColor, fileout) {
  g = ggplot(df, aes_string(x=colNameX, y=colNameY, color=colNameColor)) +
    geom_point() +
    scale_colour_gradientn(colours=rainbow(4))
  ggsave(fileout, dpi=300)
  return(g)
```

I suspect the problem is caused by `scale_colour_gradientn(colours=rainbow(4))`

**Comment by wikiselev** [comment]
maybe check this out:
http://stackoverflow.com/questions/23003527/weird-ggplot2-error-empty-raster

**Comment by pdp10** [comment]
aha I was reading that too! :)

**Comment by pdp10** [comment]
It seems a recent bug as some of those comments are dated 2015. Possibly the version of grid/ggplot2 in the cluster is an old one.

**Comment by pdp10** [comment]
Very weird indeed. 

Thanks for your help!
